services:
  - type: web
    name: coarify
    runtime: node
    plan: free
    region: oregon
    buildCommand: bash -c 'apt-get update && apt-get install -y ffmpeg && npm install && cd frontend && npm install && npm run build && cd ..'
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
