services:
  - type: web
    name: coarify
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && cd frontend && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
